export { default as Home } from './page/Home';
export { default as Sidebar } from './Navbar/Sidebar';
export { default as Login} from './page/Login';
export { default as Mainpage} from './Mainpage';
export { default as Footer } from './Navbar/Footer';
export { default as Request } from './page/Request';
export { default as Logout } from './page/Logout';
export { default as Audit } from './page/Audit';
export { default as AddUser } from './page/AddUser';
export { default as Header  } from './Navbar/Header';        
export { default as Profile } from './page/Profile' ;       
export { default as Locations } from './page/Locations';
export { default as NewAudit } from './page/NewAudit';
export { default as Stockaud } from './page/Stockaud';
export { default as Auditsystem } from './page/Auditsystem';
export { default as Addstock } from './page/Addstock';
export { default as StocksAtLocation } from './page/StocksAtLocation';
